version: "3.5"
services:
  frontend:
    container_name: frontend_exro
    build: 
      dockerfile: Dockerfile
      context: ./front
    volumes:
      - ./front:/usr/src/front-app
      - ./front/package.json:/usr/src/front-app/package.json
      - /usr/src/front-app/node_modules
    ports:
      - "9090:9090"
    networks:
      - network_exro

  backend:
    container_name: backend_exro
    build: 
      dockerfile: Dockerfile
      context: ./back
    volumes:
      - ./back/:/usr/src/back-app
      - ./back/composer.json:/usr/src/back-app/composer.json
      - ./back/composer.lock:/usr/src/back-app/composer.lock
      - ./back/public:/usr/src/back-app/public
      - /usr/src/back-app/vendor
    ports:
      - "8000:8000"
    networks:
      - network_exro

networks:
  network_exro: {}